// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Vendas.Model
{
    public partial class DB_VENDASContext : DbContext
    {
        public DB_VENDASContext()
        {
        }

        public DB_VENDASContext(DbContextOptions<DB_VENDASContext> options)
            : base(options)
        {
        }

        public virtual DbSet<TBCategorias> TBCategorias { get; set; }
        public virtual DbSet<TBClientes> TBClientes { get; set; }
        public virtual DbSet<TBItens> TBItens { get; set; }
        public virtual DbSet<TBPedidos> TBPedidos { get; set; }
        public virtual DbSet<TBProdutos> TBProdutos { get; set; }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured)
            {
#warning To protect potentially sensitive information in your connection string, you should move it out of source code. You can avoid scaffolding the connection string by using the Name= syntax to read it from configuration - see https://go.microsoft.com/fwlink/?linkid=2131148. For more guidance on storing connection strings, see http://go.microsoft.com/fwlink/?LinkId=723263.
                optionsBuilder.UseSqlServer("Data Source=JACKNOTEBOOK\\SQLEXPRESS;Initial Catalog=DB_VENDAS;Integrated Security=True");
            }
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<TBItens>(entity =>
            {
                entity.HasOne(d => d.IdPedidoNavigation)
                    .WithMany(p => p.TBItens)
                    .HasForeignKey(d => d.IdPedido)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK__TBItens__IdPedid__2D27B809");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}