using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
namespace Vendas.Model
{
    public class TBClientesBase
    {
        [StringLength(25)]
        [Unicode(false)]
        [Display(Name = "Telefone")]
        public string Email { get; set; }
    }
}