// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Diagnostics;
using Microsoft.EntityFrameworkCore;

namespace Vendas.Model
{
    [DebuggerDisplay($"{{{nameof(GetDebuggerDisplay)}(),nq}}")]
    public partial class TBClientes
    {
        [Key]

        //[StringLength(15)]
        //[Unicode(false)]
        //[Display(Name = "Id")]
        public int Id { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        [Display(Name = "Documento")]
        public string Documento { get; set; }

        [StringLength(20)]
        [Unicode(false)]
        [Display(Name = "Nome")]
        public string Nome { get; set; }

        [StringLength(25)]
        [Unicode(false)]
        [Display(Name = "Telefone")]
        public string Telefone { get; set; }

        [StringLength(50)]
        [Unicode(false)]
        [Display(Name = "Email")]
        public string Email { get; set; }
      
        private string GetDebuggerDisplay()
        {
            return ToString();
        }
    }

}


