// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Vendas.Model
{
    public partial class TBItens
    {
        [Key]
        public int Id { get; set; }
        public int IdPedido { get; set; }
        public int IdProduto { get; set; }
        public double Quantidade { get; set; }

        [ForeignKey("IdPedido")]
        [InverseProperty("TBItens")]
        public virtual TBPedidos IdPedidoNavigation { get; set; }
    }
}